# Generated by Django 5.2.6 on 2025-09-30 13:21

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('thumbnail', models.ImageField(upload_to='news_images/')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('tanggal', models.DateField()),
                ('news_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.newscategory')),
            ],
        ),
    ]
