# Generated by Django 5.2.6 on 2025-09-30 13:48

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsCategory',
            new_name='KategoriPaket',
        ),
        migrations.CreateModel(
            name='Paket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('thumbnail', models.ImageField(upload_to='paket_images/')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('tanggal', models.DateField()),
                ('paket_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.kategoripaket')),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
