# Generated by Django 5.2.6 on 2025-09-30 14:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_rename_newscategory_kategoripaket_paket_delete_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paket',
            name='tanggal',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
