# Generated by Django 5.2.6 on 2025-09-30 16:04

import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_alter_paket_tanggal'),
    ]

    operations = [
        migrations.CreateModel(
            name='kapal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('thumbnail', models.ImageField(upload_to='kapal_images/')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('kapal_kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.kategoripaket')),
            ],
        ),
    ]
