# Generated by Django 5.2.6 on 2025-10-01 14:05

import tour.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_fotogaleri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kapal',
            name='thumbnail',
            field=models.ImageField(upload_to=tour.models.upload_kapal_thumbnail),
        ),
        migrations.AlterField(
            model_name='paket',
            name='thumbnail',
            field=models.ImageField(upload_to=tour.models.upload_paket_thumbnail),
        ),
    ]
