# Generated by Django 5.2.6 on 2025-10-03 05:39

import ckeditor_uploader.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_alter_kapal_thumbnail_alter_paket_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('thumbnail', models.ImageField(upload_to='blog_foto/')),
            ],
        ),
    ]
