# Generated by Django 5.2.6 on 2025-10-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0007_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
